/* MICKS PICKS — LOTTO PROPS ENGINE
   Separate tracking for lotto/ladder/high-risk prop cards.
*/
const LOTTO_SHEET_ID='15txBM8qsck7f0ZA_za7xYEykBxKpuq0no3x7yHcKNeE';
const LOTTO_GIDS={active:'0',results:'1579113575',vip:'210503117',props:'695299787'};
const LOTTO_ALIASES={date:['Date','Posted Date','Pick Date'],sport:['Sport'],league:['League','Sport League'],game:['Game','Matchup','Event'],pick:['Pick','Play','Selection'],market:['Market','Bet Type','Odds Market'],betType:['Bet Type','Market','Type'],odds:['Odds','Price'],sportsbook:['Sportsbook','Book','Bookmaker'],grade:['Grade','Rating'],units:['Units','Unit','Stake'],bestNumber:['Best Number','Best #','Best Line'],status:['Status'],result:['Result','Outcome'],profitLoss:['Profit/Loss','Profit Loss','P/L','PL'],writeup:['Writeup','Write Up','Public Writeup','Summary'],fullAnalysis:['Full Analysis','Analysis','VIP Analysis'],access:['Access','Tier'],featured:['Featured','Feature','Featured?'],closingNumber:['Closing #','Closing Number','Closing Line']};
function lCsv(gid){return `https://docs.google.com/spreadsheets/d/${LOTTO_SHEET_ID}/export?format=csv&gid=${gid}&cache=${Date.now()}`}
function lEsc(s){return String(s||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function lClean(s){return String(s||'').trim().toLowerCase().replace(/\s+/g,' ')}
function lCompact(s){return lClean(s).replace(/[^a-z0-9]/g,'')}
function lNum(v){const n=parseFloat(String(v||'').replace(/[^0-9.+-]/g,''));return Number.isFinite(n)?n:0}
function lHas(v){return String(v||'').trim().length>0}
function lSet(id,v){const el=document.getElementById(id); if(el) el.textContent=v}
function lDateVal(v){const s=String(v||'').trim(); if(!s)return 0; let m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/); if(m)return new Date(+m[1],+m[2]-1,+m[3]).getTime(); m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})/); if(m){let y=+m[3]; if(y<100)y+=2000; return new Date(y,+m[1]-1,+m[2]).getTime()} const d=new Date(s); return Number.isNaN(d.getTime())?0:d.getTime()}
function lFmtDate(v){const t=lDateVal(v); if(!t)return lEsc(v||''); const d=new Date(t); return `${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}/${d.getFullYear()}`}
function lParseCSV(text){const rows=[];let row=[],cur='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cur+='"';i++}else if(c==='"'){q=!q}else if(c===','&&!q){row.push(cur);cur=''}else if((c==='\n'||c==='\r')&&!q){if(cur!==''||row.length){row.push(cur);rows.push(row);row=[];cur=''}if(c==='\r'&&n==='\n')i++}else cur+=c}if(cur!==''||row.length){row.push(cur);rows.push(row)}return rows}
function lNorm(h){return String(h||'').trim().toLowerCase().replace(/\s+/g,' ').replace(/[^\w#/% ]/g,'')}
function lAlias(headers,aliases){return headers.find(h=>aliases.some(a=>lNorm(a)===lNorm(h)))}
function lObjects(rows,source){if(!rows.length)return[];const headers=rows[0].map(h=>String(h||'').trim());return rows.slice(1).map(r=>{const raw={};headers.forEach((h,i)=>raw[h]=String(r[i]||'').trim());const obj={_raw:raw,_sourceTab:source};Object.entries(LOTTO_ALIASES).forEach(([k,aliases])=>{const real=lAlias(headers,aliases);obj[k]=real?String(raw[real]||'').trim():''});return obj}).filter(r=>Object.values(r._raw||{}).some(v=>String(v||'').trim()!==''))}
async function lRows(gid,source){const res=await fetch(lCsv(gid),{cache:'no-store'});const txt=await res.text();if(txt.toLowerCase().includes('<html'))throw new Error(source+' unavailable');return lObjects(lParseCSV(txt),source)}
function lVip(row){return lClean(`${row.access||''} ${row.featured||''} ${row._sourceTab||''}`).includes('vip')}
function lResultText(row){return lClean(`${row.result||''} ${row.status||''}`)}
function lWin(row){const pl=lNum(row.profitLoss); if(pl>0)return true; const r=lResultText(row); return r.includes('win')||r.includes('won')||r.includes('cash')||r==='w'}
function lLoss(row){const pl=lNum(row.profitLoss); if(pl<0)return true; const r=lResultText(row); return r.includes('loss')||r.includes('lost')||r.includes('failed')||r==='l'}
function lPush(row){const r=lResultText(row); return r.includes('push')||r.includes('void')||r.includes('cancel')}
function lClosed(row){return lWin(row)||lLoss(row)||lPush(row)||lClean(row.status).includes('graded')||lClean(row.status).includes('closed')}
function lDisplay(row){if(lWin(row))return'Win';if(lLoss(row))return'Loss';if(lPush(row))return'Push/Void';return row.result||row.status||'Pending'}
function lClass(v){const r=lClean(v); if(r.includes('win'))return'status-win'; if(r.includes('loss'))return'status-loss'; return'status-pending'}
function isLottoProp(row){const t=lClean(`${row.betType} ${row.market} ${row.pick} ${row.writeup} ${row.fullAnalysis}`);const must=['lotto','ladder','longshot','long shot','sprinkle','moonshot','high risk','high-risk','hr ladder','home run ladder','sog ladder','alt pra','alt points','alt rebounds','alt assists','same game prop','sgp prop','prop parlay','plus-money prop','plus money prop']; if(must.some(w=>t.includes(w)))return true; if(t.includes('home run')&&t.includes('over'))return true; if(t.includes('anytime touchdown')||t.includes('first touchdown'))return true; return false}
function lActive(row){const s=lClean(row.status);return lHas(row.pick)&&!lClosed(row)&&!['void','cancelled','canceled','delete','removed'].some(x=>s.includes(x))}
function lKey(row){return [lDateVal(row.date),row.league||row.sport||'',row.game||'',row.pick||'',lDisplay(row),lVip(row)?'vip':'public'].map(lCompact).join('|')}
function lDedupe(rows){const best=new Map();rows.forEach(r=>{const k=lKey(r); if(!k)return; const e=best.get(k); if(!e){best.set(k,r);return} const rs=(lWin(r)?10:0)+(lVip(r)?5:0)+(r._sourceTab==='Props Results'?4:0)+(r._sourceTab==='VIP Archive'?3:0)+(lHas(r.fullAnalysis)?2:0)+(lDateVal(r.date)/1e15); const es=(lWin(e)?10:0)+(lVip(e)?5:0)+(e._sourceTab==='Props Results'?4:0)+(e._sourceTab==='VIP Archive'?3:0)+(lHas(e.fullAnalysis)?2:0)+(lDateVal(e.date)/1e15); if(rs>es)best.set(k,r)});return Array.from(best.values())}
function lStats(rows,active){const graded=rows.filter(r=>lHas(r.pick)&&(lWin(r)||lLoss(r)));const w=graded.filter(lWin).length,l=graded.filter(lLoss).length,total=w+l;const units=graded.reduce((s,r)=>s+lNum(r.profitLoss),0);return{record:total?`${w}-${l}`:'--',winRate:total?`${Math.round(w/total*100)}%`:'--',units:total||units?`${units>0?'+':''}${units.toFixed(2)}u`:'--',active:active.length||'--',graded:total||'--'}}
function lCard(row){return `<div class="pick-card locked-card"><div class="kicker">${lVip(row)?'VIP Lotto Prop':'Lotto Prop'}</div><div class="pick-title">${lEsc(row.pick||'Lotto Prop')}</div><p style="color:var(--muted);line-height:1.5">${lEsc(row.game||'')}</p><div class="metric-grid"><div class="metric"><strong>${lEsc(row.odds||'--')}</strong><span>Odds</span></div><div class="metric"><strong>${lEsc(row.sportsbook||'--')}</strong><span>Book</span></div><div class="metric"><strong>${lEsc(row.bestNumber||'--')}</strong><span>Best Line</span></div><div class="metric"><strong class="${lClass(lDisplay(row))}">${lEsc(lDisplay(row))}</strong><span>Status</span></div></div><p style="color:#e7dcc4;line-height:1.55;margin-top:14px">${lEsc(row.writeup||row.fullAnalysis||'High-upside lotto prop angle.')}</p></div>`}
function renderLottoGrid(id,rows){const el=document.getElementById(id);if(!el)return;const usable=rows.filter(lActive).sort((a,b)=>lDateVal(b.date)-lDateVal(a.date)).slice(0,12);el.innerHTML=usable.length?usable.map(lCard).join(''):'<div class="empty">No active lotto props loaded right now.</div>'}
function renderLottoResults(id,rows){const el=document.getElementById(id);if(!el)return;const usable=lDedupe(rows).filter(r=>lHas(r.pick)&&lClosed(r)).sort((a,b)=>lDateVal(b.date)-lDateVal(a.date)).slice(0,100);if(!usable.length){el.innerHTML='<tr><td colspan="8">No lotto prop results loaded.</td></tr>';return}el.innerHTML=usable.map(r=>`<tr><td>${lFmtDate(r.date)}</td><td>${lEsc(r.league||r.sport||'')}</td><td><strong>${lEsc(r.pick||'')}</strong><br><span style="color:var(--muted)">${lEsc(r.game||'')}</span></td><td>${lEsc(r.grade||'')}</td><td class="${lClass(lDisplay(r))}">${lEsc(lDisplay(r))}</td><td>${lEsc(r.profitLoss||'')}</td><td>${lEsc(r.closingNumber||r.bestNumber||'')}</td><td>${lEsc(r._sourceTab||'')}${lVip(r)?' / VIP':''}</td></tr>`).join('')}
async function bootLottoProps(){if(!document.body.classList.contains('page-bg-props_lab'))return;try{const [active,results,vip,props]=await Promise.all([lRows(LOTTO_GIDS.active,'Active Picks'),lRows(LOTTO_GIDS.results,'Results Archive').catch(()=>[]),lRows(LOTTO_GIDS.vip,'VIP Archive').catch(()=>[]),lRows(LOTTO_GIDS.props,'Props Results').catch(()=>[])]);const all=lDedupe(props.concat(vip,results,active)).filter(isLottoProp);const act=all.filter(lActive);const stats=lStats(all,act);lSet('lottoRecord',stats.record);lSet('lottoWinRate',stats.winRate);lSet('lottoTotalUnits',stats.units);lSet('lottoActiveCount',stats.active);lSet('lottoGradedCount',stats.graded);renderLottoGrid('lottoPropsGrid',all);renderLottoResults('lottoPropsResultsBody',all)}catch(e){const el=document.getElementById('lottoPropsGrid');if(el)el.innerHTML='<div class="empty">Lotto props could not load.</div>';console.error('Lotto Props error:',e)}}
bootLottoProps();setInterval(bootLottoProps,30000);
