import { google } from 'googleapis'

const DEFAULT_SPREADSHEET_ID = '15txBM8qsck7f0ZA_za7xYEykBxKpuq0no3x7yHcKNeE'

const TABLE_TABS = {
  picks: ['GOOGLE_SHEETS_PICKS_TAB', 'GOOGLE_SHEETS_MASTER_PICKS_TAB', 'SHEETS_PICKS_TAB'],
  master: ['GOOGLE_SHEETS_PICKS_TAB', 'GOOGLE_SHEETS_MASTER_PICKS_TAB', 'SHEETS_PICKS_TAB'],
  masterPicks: ['GOOGLE_SHEETS_PICKS_TAB', 'GOOGLE_SHEETS_MASTER_PICKS_TAB', 'SHEETS