import { runAirtableDiagnostics } from '../lib/airtableDiagnostics.js'
import { setupAirtableBase } from '../lib/airtableSetup.js'
import { runAirtableTokenTest } from '../lib/airtableTokenTest.js'
import { archiveClosedBets } from '../lib/archiveClosedBets.js'
import { runClosingOddsWorker } from '../lib/closingOddsWorker.js'
import { generateMicksPicks } from '../lib/micksPicksGenerator.js'
import {
  ingestPicksToAirtable,
  runMicksSync,
  syncAirtableOperatorToSheets,
  syncSheetsToAirtable
} from '../lib/micksSyncAutomation.js'
import { assertSyncAuthorized, sendError } from '../lib/syncAuth.js'

function param(req, name) {
  return req.query?.[name] ?? req.body?.[name]
}

function boolParam(req, name) {
  const value = param(req, name)
  return value === true || ['1', 'true', 'yes'].includes(String(value || '').toLowerCase())
}

function todayKey() {
  return new Date().toISOString().slice(0, 10)
}

function numberParam(req, name, fallback) {
  const value = param(req, name)
  if (value === undefined || value === null || value === '') return fallback
  const number = Number(String(value).replace(/[^\d.+-]/g, ''))
  return Number.isFinite(number) ? number : fallback
}

function envNumber(name, fallback) {
  const value = Number(process.env[name])
  return Number.isFinite(value) ? value : fallback
}

function runMicksPicksFailure(req, error, stage = 'sourceAcquisition') {
  const includeProps = boolParam(req, 'includeProps')
  const includeLotto = boolParam(req, 'includeLotto')
  const includeLottoProps = boolParam(req, 'includeLottoProps')
  const overrideUsed = boolParam(req, 'overrideRateGuard')
  const windowHours = envNumber('MICKS_PICKS_RATE_WINDOW_HOURS', 5)
  const message = error?.message || 'Run Micks Picks failed before a safe result was returned.'
  return {
    success: false,
    action: 'run-micks-picks',
    stage,
    mode: String(param(req, 'mode') || 'review'),
    errors: [{ message }],
    warnings: ['Run Micks Picks returned a safe JSON error instead of a platform error.'],
    tokenBudget: {
      openAiRuns: 0,
      propsSecondPass: false,
      candidatePoolTarget: numberParam(req, 'maxCandidates', 12),
      maxRuns: overrideUsed
        ? envNumber('MICKS_PICKS_MAX_OPENAI_CALLS_PER_RUN', 1)
        : envNumber('MICKS_PICKS_MAX_OPENAI_CALLS_PER_RUN', 1),
      deepMode: boolParam(req, 'deepMode'),
      perRunBudget: envNumber('MICKS_PICKS_PER_RUN_TOKEN_BUDGET', 7000),
      maxOutputTokens: envNumber('MICKS_PICKS_MAX_OUTPUT_TOKENS', 1200)
    },
    rateBudget: {
      windowHours,
      runsUsed: 0,
      runsRemaining: 0,
      cachedResultUsed: false,
      overrideUsed,
      nextAllowedRunAt: new Date(Date.now() + windowHours * 60 * 60 * 1000).toISOString()
    },
    sourceAcquisition: {
      boardOddsPass: 'skipped',
      injuryPass: 'skipped',
      propsPass: includeProps ? 'skipped' : 'skipped',
      skippedReasons: [message],
      sourceConfidence: { high: 0, medium: 0, low: 0 }
    },
    routeOutputs: {
      vipReview: [],
      freeReview: [],
      propsReview: [],
      lottoReview: [],
      lottoPropsReview: [],
      longshotsReview: []
    },
    propsStatus: {
      requested: includeProps,
      status: includeProps ? 'incomplete' : 'not_requested',
      rawFound: 0,
      verified: 0,
      missing: includeProps ? ['source acquisition failed'] : [],
      reason: message
    },
    lottoStatus: {
      requested: includeLotto,
      created: 0,
      reason: includeLotto ? message : ''
    },
    lottoPropsStatus: {
      requested: includeLottoProps,
      created: 0,
      reason: includeLottoProps ? message : ''
    },
    cards: [],
    rawCandidatePool: [],
    candidatePool: [],
    eligibleCandidatePool: [],
    rawCandidatesFound: 0,
    candidatePoolCount: 0,
    eligibleCandidatePoolCount: 0,
    publishEligibleCount: 0,
    reviewEligibleCount: 0,
    watchlistCount: 0,
    passCount: 0,
    backup: { skipped: true, reason: 'Run Micks Picks failed before Airtable write.' }
  }
}

function quickTestPickPayload(req) {
  const date = String(param(req, 'date') || todayKey())
  return {
    date,
    picks: [{
      date,
      sport: 'NBA',
      league: 'NBA',
      game: String(param(req, 'game') || 'Micks Picks Test Game'),
      pick: String(param(req, 'pick') || 'Micks Picks Test ML'),
      betType: 'Moneyline',
      access: String(param(req, 'access') || 'Free'),
      odds: numberParam(req, 'odds', -110),
      sportsbook: 'BetRivers',
      units: numberParam(req, 'units', 1),
      grade: 'A',
      confidence: 60,
      evEdge: 2.5,
      status: 'Active',
      result: 'Pending',
      archiveStatus: 'Active',
      writeup: 'Automated Airtable ingest test card.',
      fullAnalysis: 'This confirms Airtable-first ingestion can create populated Master Picks rows.',
      marketNotes: 'Quick test only.',
      injuryNotes: '',
      sourceVerification: 'Generated by quick-test-pick admin action.'
    }]
  }
}

function generateMicksPicksOptions(req) {
  return {
    ...(req.body || {}),
    date: param(req, 'date'),
    sport: param(req, 'sport'),
    league: param(req, 'league'),
    mode: param(req, 'mode') || 'review',
    access: param(req, 'access') || 'auto',
    maxPicks: param(req, 'maxPicks') || 3,
    maxCandidates: param(req, 'maxCandidates'),
    maxVipPicks: param(req, 'maxVipPicks'),
    maxFreePicks: param(req, 'maxFreePicks'),
    maxProps: param(req, 'maxProps'),
    maxLottoCards: param(req, 'maxLottoCards'),
    maxLottoProps: param(req, 'maxLottoProps'),
    maxLongshots: param(req, 'maxLongshots'),
    includeProps: param(req, 'includeProps'),
    includeLotto: param(req, 'includeLotto'),
    includeLottoProps: param(req, 'includeLottoProps'),
    includeLongLotto: param(req, 'includeLongLotto'),
    includeLongshots: param(req, 'includeLongshots'),
    allowReviewLotto: param(req, 'allowReviewLotto'),
    deepMode: param(req, 'deepMode'),
    forceRefresh: param(req, 'forceRefresh'),
    overrideRateGuard: param(req, 'overrideRateGuard'),
    allowSample: boolParam(req, 'allowSample'),
    dryRun: boolParam(req, 'dryRun')
  }
}

function runMicksPicksOptions(req) {
  return {
    ...generateMicksPicksOptions(req),
    command: 'run-micks-picks',
    mode: param(req, 'mode') || (['1', 'true', 'yes'].includes(String(process.env.MICKS_PICKS_AUTO_PUBLISH || '').toLowerCase()) ? 'publish' : 'review')
  }
}

const ACTIONS = {
  'run-sync': req => runMicksSync({
    dryRun: boolParam(req, 'dryRun')
  }),
  'ingest-picks': req => ingestPicksToAirtable(req.body || {}, {
    dryRun: boolParam(req, 'dryRun')
  }),
  'quick-test-pick': req => ingestPicksToAirtable(quickTestPickPayload(req), {
    dryRun: boolParam(req, 'dryRun')
  }),
  'generate-micks-picks': req => generateMicksPicks(generateMicksPicksOptions(req)),
  'run-micks-picks': req => generateMicksPicks(runMicksPicksOptions(req)),
  'sync-sheets-to-airtable': req => syncSheetsToAirtable({
    dryRun: boolParam(req, 'dryRun'),
    backfill: boolParam(req, 'backfill')
  }),
  'import-sheets-backfill': req => syncSheetsToAirtable({
    dryRun: boolParam(req, 'dryRun'),
    backfill: true
  }),
  'sync-airtable-to-sheets': req => syncAirtableOperatorToSheets({
    dryRun: boolParam(req, 'dryRun')
  }),
  'airtable-diagnostics': () => runAirtableDiagnostics(),
  'airtable-token-test': () => runAirtableTokenTest(),
  'setup-airtable-base': req => setupAirtableBase({
    dryRun: boolParam(req, 'dryRun')
  }),
  'archive-closed-bets': req => archiveClosedBets({
    dryRun: boolParam(req, 'dryRun')
  }),
  'closing-odds-worker': req => runClosingOddsWorker({
    dryRun: boolParam(req, 'dryRun')
  })
}

export default async function handler(req, res) {
  let action = ''
  try {
    assertSyncAuthorized(req)
    const isCron = req.headers?.['x-vercel-cron'] ||
      String(req.headers?.['user-agent'] || '').toLowerCase().includes('vercel-cron')
    action = String(param(req, 'action') || (isCron ? 'run-sync' : '')).trim()
    const runAction = ACTIONS[action]

    if (!runAction) {
      res.status(400).json({
        success: false,
        error: 'Unknown admin action',
        actions: Object.keys(ACTIONS)
      })
      return
    }

    const result = await runAction(req)
    res.status(200).json({
      success: result?.success !== false,
      action,
      ...result
    })
  } catch (error) {
    console.error(error)
    if (error?.statusCode !== 401 && (action === 'run-micks-picks' || String(param(req, 'action') || '') === 'run-micks-picks')) {
      res.status(200).json(runMicksPicksFailure(req, error))
      return
    }
    sendError(res, error)
  }
}
