import { runAirtableDiagnostics } from '../lib/airtableDiagnostics.js'
import { setupAirtableBase } from '../lib/airtableSetup.js'
import { runAirtableTokenTest } from '../lib/airtableTokenTest.js'
import { archiveClosedBets } from '../lib/archiveClosedBets.js'
import { runClosingOddsWorker } from '../lib/closingOddsWorker.js'
import {
  ingestPicksToAirtable,
  runMicksSync,
  syncAirtableOperatorToSheets,
  syncSheetsToAirtable
} from '../lib/micksSyncAutomation.js'
import { assertSyncAuthorized, sendError } from '../lib/syncAuth.js'

function param(req, name) {
  return req.query?.[name] ?? req.body?.[name]
}

function boolParam(req, name) {
  const value = param(req, name)
  return value === true || ['1', 'true', 'yes'].includes(String(value || '').toLowerCase())
}

function todayKey() {
  return new Date().toISOString().slice(0, 10)
}

function numberParam(req, name, fallback) {
  const value = param(req, name)
  if (value === undefined || value === null || value === '') return fallback
  const number = Number(String(value).replace(/[^\d.+-]/g, ''))
  return Number.isFinite(number) ? number : fallback
}

function quickTestPickPayload(req) {
  const date = String(param(req, 'date') || todayKey())
  return {
    date,
    picks: [{
      date,
      sport: 'NBA',
      league: 'NBA',
      game: String(param(req, 'game') || 'Micks Picks Test Game'),
      pick: String(param(req, 'pick') || 'Micks Picks Test ML'),
      betType: 'Moneyline',
      access: String(param(req, 'access') || 'Free'),
      odds: numberParam(req, 'odds', -110),
      sportsbook: 'BetRivers',
      units: numberParam(req, 'units', 1),
      grade: 'A',
      confidence: 60,
      evEdge: 2.5,
      status: 'Active',
      result: 'Pending',
      archiveStatus: 'Active',
      writeup: 'Automated Airtable ingest test card.',
      fullAnalysis: 'This confirms Airtable-first ingestion can create populated Master Picks rows.',
      marketNotes: 'Quick test only.',
      injuryNotes: '',
      sourceVerification: 'Generated by quick-test-pick admin action.'
    }]
  }
}

const ACTIONS = {
  'run-sync': req => runMicksSync({
    dryRun: boolParam(req, 'dryRun')
  }),
  'ingest-picks': req => ingestPicksToAirtable(req.body || {}, {
    dryRun: boolParam(req, 'dryRun')
  }),
  'quick-test-pick': req => ingestPicksToAirtable(quickTestPickPayload(req), {
    dryRun: boolParam(req, 'dryRun')
  }),
  'sync-sheets-to-airtable': req => syncSheetsToAirtable({
    dryRun: boolParam(req, 'dryRun'),
    backfill: boolParam(req, 'backfill')
  }),
  'import-sheets-backfill': req => syncSheetsToAirtable({
    dryRun: boolParam(req, 'dryRun'),
    backfill: true
  }),
  'sync-airtable-to-sheets': req => syncAirtableOperatorToSheets({
    dryRun: boolParam(req, 'dryRun')
  }),
  'airtable-diagnostics': () => runAirtableDiagnostics(),
  'airtable-token-test': () => runAirtableTokenTest(),
  'setup-airtable-base': req => setupAirtableBase({
    dryRun: boolParam(req, 'dryRun')
  }),
  'archive-closed-bets': req => archiveClosedBets({
    dryRun: boolParam(req, 'dryRun')
  }),
  'closing-odds-worker': req => runClosingOddsWorker({
    dryRun: boolParam(req, 'dryRun')
  })
}

export default async function handler(req, res) {
  try {
    assertSyncAuthorized(req)
    const isCron = req.headers?.['x-vercel-cron'] ||
      String(req.headers?.['user-agent'] || '').toLowerCase().includes('vercel-cron')
    const action = String(param(req, 'action') || (isCron ? 'run-sync' : '')).trim()
    const runAction = ACTIONS[action]

    if (!runAction) {
      res.status(400).json({
        success: false,
        error: 'Unknown admin action',
        actions: Object.keys(ACTIONS)
      })
      return
    }

    const result = await runAction(req)
    res.status(200).json({
      success: result?.success !== false,
      action,
      ...result
    })
  } catch (error) {
    console.error(error)
    sendError(res, error)
  }
}
