const VIP_PICKS = [
  {
    date: "2026-07-06", sport: "Soccer", league: "FIFA World Cup", category: "VIP", access: "VIP", section: "vip", originalTable: "VIP",
    game: "Spain vs Portugal", pick: "Spain to Advance", cardTitle: "Spain to Advance", betType: "To Advance", market: "To Advance", odds: "-210", units: "1.00u", grade: "A-", confidence: "8.6/10", bestNumber: "-210", lineNumber: "-210", noBetCutoff: "-240 or worse", status: "Active", releaseStatus: "VIP Released", sportsbook: "Circa / shop best advance price", risk: "Medium", featured: "Yes",
    shortAnalysis: "Spain is the preferred side, but the advance market is safer than Spain 90-minute ML because knockout draw risk matters.",
    writeup: "Spain to Advance is the cleanest VIP expression on the World Cup board. Spain profiles as the better side, but this is knockout soccer, so forcing a 90-minute moneyline creates unnecessary draw risk. The advance market protects the position through extra time and penalties while still backing the better team to survive the tie.",
    analysis: "Spain to Advance is the preferred VIP structure over Spain 90-minute ML because the matchup supports Spain as the stronger side without requiring them to win inside regulation. Circa shows Spain as the regulation favorite and also prices Spain to advance as the clear but not overwhelming favorite. That matters because the draw probability is meaningful in a Portugal-Spain knockout matchup. The goal is not to overpay for narrative or force a side at a fragile number. Spain to Advance protects against a 90-minute draw while still capturing the core handicap: Spain has the better tournament profile and should be trusted more to survive the tie. Micks Verdict: VIP A-, 1.00u. Play around -210. Playable to -225. Pass if it gets worse than -240.",
    fullAnalysis: "Spain to Advance is the preferred VIP structure over Spain 90-minute ML because the matchup supports Spain as the stronger side without requiring them to win inside regulation. Circa shows Spain as the regulation favorite and also prices Spain to advance as the clear but not overwhelming favorite. That matters because the draw probability is meaningful in a Portugal-Spain knockout matchup.\n\nThe goal is not to overpay for narrative or force a side at a fragile number. Spain to Advance protects against a 90-minute draw while still capturing the core handicap: Spain has the better tournament profile and should be trusted more to survive the tie.\n\nThis is exactly why the advance market is the Micks Picks version. If Spain wins in regulation, the ticket cashes. If the match becomes cagey and reaches extra time or penalties, the position is still alive instead of dying on the 90-minute draw. That protection matters in a knockout setting with two high-end teams.\n\nMicks Verdict: VIP A-, 1.00u. Play around -210. Playable to -225. Pass if it gets worse than -240.",
    birthdayNotes: "July 6 football birthdays, for example Ze Roberto and Rory Delap, are narrative only and should not be treated as edge."
  },
  {
    date: "2026-07-06", sport: "Soccer", league: "FIFA World Cup", category: "VIP", access: "VIP", section: "vip", originalTable: "VIP",
    game: "USA vs Belgium", pick: "Over 2.5 Goals", cardTitle: "USA/Belgium Over 2.5 Goals", betType: "Total", market: "Total", odds: "-125", units: "0.75u", grade: "B+", confidence: "8.1/10", bestNumber: "-125", lineNumber: "Over 2.5", noBetCutoff: "-140 or worse", status: "Active", releaseStatus: "VIP Released", sportsbook: "Circa / shop best total", risk: "Medium", featured: "Yes",
    shortAnalysis: "The better angle is goals instead of a side. Both attacks have enough chance creation to push this over.",
    writeup: "USA vs Belgium profiles as an open knockout match with attacking talent on both sides. Instead of forcing a winner in a match where both teams are close to pick em to advance, the cleaner play is Over 2.5 goals.",
    analysis: "USA/Belgium Over 2.5 remains the best total angle on the July 6 World Cup board. Both sides have enough attacking quality to create chances, and the market does not give either team a dominant side edge. That makes the total more attractive than trying to pick the winner. The key handicap is game state. If either team scores first, the match can open quickly because the trailing side has enough attacking pieces to respond. Belgium has elite chance creation profiles, while the USA has enough pace and front-line threat to make this more of a transition game than a cagey 1-0 profile. Micks Verdict: VIP B+, 0.75u. Play Over 2.5 around -125. Playable to -135. Pass at -140 or worse.",
    fullAnalysis: "USA/Belgium Over 2.5 remains the best total angle on the July 6 World Cup board. Both sides have enough attacking quality to create chances, and the market does not give either team a dominant side edge. That makes the total more attractive than trying to pick the winner.\n\nThe key handicap is game state. If either team scores first, the match can open quickly because the trailing side has enough attacking pieces to respond. Belgium has high-end chance creation and individual attacking quality, while the USA has enough pace and front-line threat to create transition chances and force Belgium into defending space.\n\nThis is not a spot where Micks Picks needs to force USA or Belgium as the side. The better angle is that the matchup can produce enough quality looks for three goals, especially if the first goal arrives before the match settles into a late knockout-game shell.\n\nMicks Verdict: VIP B+, 0.75u. Play Over 2.5 around -125. Playable to -135. Pass at -140 or worse.",
    birthdayNotes: "July 6 football birthdays, for example Ze Roberto and Rory Delap, are narrative only and should not be treated as edge."
  }
]

const FREE_PICKS = [
  {
    date: "2026-07-06", sport: "WNBA", league: "WNBA", category: "Free", access: "Free", section: "free", originalTable: "Master Picks",
    game: "Connecticut Sun vs Minnesota Lynx", pick: "Minnesota Lynx -13", cardTitle: "Minnesota Lynx -13", betType: "Spread", market: "Spread", odds: "-110", units: "0.75u", grade: "B+", confidence: "7.9/10", bestNumber: "-13", lineNumber: "-13", noBetCutoff: "-14.5 or worse", status: "Active", releaseStatus: "Free Released", sportsbook: "Circa / shop best spread", risk: "Medium-High",
    shortAnalysis: "Minnesota is clearly superior, but the spread size keeps this out of VIP.",
    writeup: "The Lynx have the clear team-strength edge, but this is still a large WNBA spread. The gap is real enough to play, but the number is too big to make it VIP.",
    analysis: "Minnesota is the clearly stronger team and the market reflects that with a heavy moneyline and a large spread. The issue is not side quality; the issue is spread tax. Laying double digits in the WNBA always creates late-game and backdoor risk. That is why this belongs on the Free card instead of the VIP card.",
    fullAnalysis: "Free-card play only. Minnesota is the clearly stronger team and the market reflects that with a heavy moneyline and a large spread. The issue is not side quality; the issue is spread tax. Laying double digits in the WNBA always creates late-game and backdoor risk.\n\nThe Lynx deserve to be favored by a wide margin, but a -13 spread can still be threatened by fourth-quarter rotation minutes, pace slowdown, and a backdoor cover. The right approach is to respect the mismatch without pretending the number is cheap.\n\nMicks Verdict: Free B+, 0.75u. Play -13. Playable to -13.5. Pass at -14.5 or worse."
  },
  {
    date: "2026-07-06", sport: "WNBA", league: "WNBA", category: "Free", access: "Free", section: "free", originalTable: "Master Picks",
    game: "Golden State Valkyries vs Washington Mystics", pick: "Golden State Valkyries -6", cardTitle: "Golden State Valkyries -6", betType: "Spread", market: "Spread", odds: "-110", units: "0.50u", grade: "B", confidence: "7.2/10", bestNumber: "-6", lineNumber: "-6", noBetCutoff: "-6.5 or worse", status: "Active", releaseStatus: "Free Released", sportsbook: "Circa / shop best spread", risk: "Medium-High",
    shortAnalysis: "Golden State is the better team, but -6 is not cheap enough for a big position.",
    writeup: "Golden State is playable at -6, but only as a controlled free-card piece. The Valkyries rate as the better team, but the number has enough spread tax to avoid overexposure.",
    analysis: "Golden State is the preferred side, but the edge is thinner at -6 than it was at earlier numbers. This should not be treated as a high-conviction VIP play because the spread is approaching the no-bet zone. The play is valid, but the stake has to stay controlled.",
    fullAnalysis: "Free-card play only. Golden State is the preferred side, but the edge is thinner at -6 than it was at earlier numbers. This should not be treated as a high-conviction VIP play because the spread is approaching the no-bet zone.\n\nThe Valkyries are the better team profile, but Washington can stay inside numbers if the pace slows or Golden State goes cold from the perimeter. At -6, the market has already priced in a good amount of the team gap.\n\nMicks Verdict: Free B, 0.50u. Play -6 or better. Pass at -6.5 or worse."
  },
  {
    date: "2026-07-06", sport: "WNBA", league: "WNBA", category: "Free", access: "Free", section: "free", originalTable: "Master Picks",
    game: "Seattle Storm vs Los Angeles Sparks", pick: "Los Angeles Sparks -4", cardTitle: "Los Angeles Sparks -4", betType: "Spread", market: "Spread", odds: "-110", units: "0.50u", grade: "B", confidence: "7.1/10", bestNumber: "-4", lineNumber: "-4", noBetCutoff: "-4.5 or worse", status: "Active", releaseStatus: "Free Released", sportsbook: "Circa / shop best spread", risk: "Medium",
    shortAnalysis: "Sparks have the home and offensive edge, but Seattle variance keeps this in Free tier.",
    writeup: "Los Angeles is playable at -4 because the Sparks have the better offensive and home-side setup. Seattle volatility keeps the stake controlled.",
    analysis: "Sparks -4 is a reasonable side at the current number, but not a premium position. Los Angeles has enough offensive edge to cover, but Seattle can trade scoring runs and make this a live spread late. The number is playable but should not be chased.",
    fullAnalysis: "Free-card play only. Sparks -4 is a reasonable side at the current number, but not a premium position. Los Angeles has enough offensive edge to cover, but Seattle can trade scoring runs and make this a live spread late.\n\nThe Sparks get the home-side and offensive setup edge, which is enough for a half-unit position. The concern is Seattle variance: if the Storm hit early threes or turn the game into a track meet, the cover can get uncomfortable.\n\nMicks Verdict: Free B, 0.50u. Play -4. Pass at -4.5 or worse."
  },
  {
    date: "2026-07-06", sport: "MLB", league: "MLB", category: "Free", access: "Free", section: "free", originalTable: "Master Picks",
    game: "Colorado Rockies vs Los Angeles Dodgers", pick: "Los Angeles Dodgers -1.5", cardTitle: "Los Angeles Dodgers -1.5", betType: "Run Line", market: "Run Line", odds: "-118", units: "0.50u", grade: "B", confidence: "7.4/10", bestNumber: "-118", lineNumber: "-1.5", noBetCutoff: "-130 or worse", status: "Active", releaseStatus: "Free Released", sportsbook: "Circa / shop best run line", risk: "Medium",
    shortAnalysis: "Dodgers ML is too expensive, so the run line is the better attack angle.",
    writeup: "Dodgers are the better side, but the moneyline is too expensive. The run line gives a better price while keeping the stake controlled because run-line favorites still carry variance.",
    analysis: "The Dodgers have a strong favorite profile against Colorado, but laying a heavy moneyline is not the Micks Picks preferred structure. The run line is the better payout route, especially against a Rockies team that can allow crooked innings. Variance stays real, so the unit size stays modest.",
    fullAnalysis: "Free-card play only. The Dodgers have a strong favorite profile against Colorado, but laying a heavy moneyline is not the Micks Picks preferred structure. The run line is the better payout route, especially against a Rockies team that can allow crooked innings.\n\nThis is a classic favorite-pricing decision. The Dodgers are the correct side, but the moneyline is taxed. Laying -1.5 creates more variance, yet it gets the position into a better price range. That is the right structure for a half-unit Free card play.\n\nMicks Verdict: Free B, 0.50u. Play Dodgers -1.5 to -125. Pass at -130 or worse."
  },
  {
    date: "2026-07-06", sport: "MLB", league: "MLB", category: "Free", access: "Free", section: "free", originalTable: "Master Picks",
    game: "New York Mets vs Atlanta Braves", pick: "Atlanta Braves ML", cardTitle: "Atlanta Braves ML", betType: "Moneyline", market: "Moneyline", odds: "-126", units: "0.50u", grade: "B", confidence: "7.5/10", bestNumber: "-126", lineNumber: "-126", noBetCutoff: "-145 or worse", status: "Active", releaseStatus: "Free Released", sportsbook: "Circa / shop best ML", risk: "Medium",
    shortAnalysis: "Braves are playable at the reasonable favorite price.",
    writeup: "Atlanta is the preferred side at a playable number. The price is fair enough to attack the Braves straight moneyline without needing a parlay.",
    analysis: "Braves ML is playable because the price is still reasonable and the matchup points toward Atlanta as the better side. The line does not carry enough edge for VIP, but it fits as a clean half-unit free-card position. The key is not chasing if the market moves past the cutoff.",
    fullAnalysis: "Free-card play only. Braves ML is playable because the price is still reasonable and the matchup points toward Atlanta as the better side. The line does not carry enough edge for VIP, but it fits as a clean half-unit free-card position.\n\nThis is a straight side at a fair number. Atlanta does not need to be forced into a parlay, and the price is not expensive enough to require a run-line alternative. It is simply a playable favorite at the current market.\n\nMicks Verdict: Free B, 0.50u. Play to -140. Pass at -145 or worse."
  },
  {
    date: "2026-07-06", sport: "MLB", league: "MLB", category: "Free", access: "Free", section: "free", originalTable: "Master Picks",
    game: "Arizona Diamondbacks vs San Diego Padres", pick: "Arizona Diamondbacks +1.5", cardTitle: "Arizona Diamondbacks +1.5", betType: "Run Line", market: "Run Line", odds: "-195", units: "0.50u", grade: "B", confidence: "7.0/10", bestNumber: "-195", lineNumber: "+1.5", noBetCutoff: "-210 or worse", status: "Active", releaseStatus: "Free Released", sportsbook: "Circa / shop best run line", risk: "Medium",
    shortAnalysis: "Prefer the plus-run-and-a-half in a competitive price range instead of laying Padres juice.",
    writeup: "Arizona +1.5 is the safer way to play a game that profiles as competitive. The juice is high, so this stays controlled at 0.50u.",
    analysis: "The Padres are favored, but the matchup is close enough that taking Arizona +1.5 has appeal. The issue is the price. At -195, this is still playable but juice-sensitive. It should not be chased if it gets worse.",
    fullAnalysis: "Free-card play only. The Padres are favored, but the matchup is close enough that taking Arizona +1.5 has appeal. The issue is the price. At -195, this is still playable but juice-sensitive. It should not be chased if it gets worse.\n\nThis is a safety-first structure. Rather than laying Padres juice in a game that can stay tight, the better angle is taking the extra run and a half with Arizona. The cost is high, which is why the cutoff is strict.\n\nMicks Verdict: Free B, 0.50u. Play around -195. Pass at -210 or worse."
  }
]

const PROPS = [
  { date: "2026-07-06", sport: "MLB/Soccer", league: "Props Lab", category: "Props", access: "Free", section: "props", originalTable: "Props Lab", game: "Props Lab", pick: "No Official Props Released", cardTitle: "No Official Props Released", betType: "Props Notice", market: "Props Hold", odds: "N/A", units: "0.00u", grade: "Pass", confidence: "Pass", bestNumber: "Need exact player and price", lineNumber: "Props held", noBetCutoff: "Do not play without exact number", status: "Hold", releaseStatus: "Props Held", sportsbook: "TBD", risk: "High", shortAnalysis: "No official props are released for this slate yet.", writeup: "Props are held. No official props are released until exact player, market, odds, and sportsbook are confirmed.", analysis: "This is a clear hold notice, not a playable prop. HR props and goal scorer props remain watchlist only because exact player names, prices, markets, and books were not confirmed.", fullAnalysis: "No official props are released for this slate yet. The earlier prop notes were watchlist ideas only, not official plays.\n\nMicks Picks should not publish vague HR or goal-scorer props as official bets. A prop needs exact player, market, odds, sportsbook, and cutoff before it becomes playable.\n\nMicks Verdict: Props held. No units." }
]

const LOTTO_PARLAYS = [
  { date: "2026-07-06", sport: "Soccer", league: "FIFA World Cup", category: "Lotto Parlay", access: "Free", section: "lotto", originalTable: "Lotto Parlays", game: "Spain / USA-Belgium", pick: "Spain to Advance + USA/Belgium Over 2.5 Goals", cardTitle: "Spain to Advance + USA/Belgium Over 2.5", betType: "Lotto Parlay", market: "2-Leg Parlay", odds: "TBD", units: "0.25u", grade: "B-", confidence: "7.3/10", bestNumber: "Best available", lineNumber: "2-leg parlay", noBetCutoff: "Do not chase if Spain exceeds -240 or Over exceeds -140", status: "Active", releaseStatus: "Lotto Released", sportsbook: "Shop best prices", risk: "High", shortAnalysis: "Best soccer parlay build using the safer Spain market and the strongest USA/Belgium total angle.", writeup: "This is the cleanest World Cup lotto build. Spain to Advance protects against knockout draw risk, while USA/Belgium Over 2.5 is the strongest total angle on the soccer board.", analysis: "This should not replace the straight VIP positions. Spain to Advance is the safer version of the Spain handicap, and USA/Belgium Over 2.5 is the cleaner angle than choosing a side. Keep the stake controlled because parlays compound risk.", fullAnalysis: "Lotto Parlay tab only. This should not replace the straight VIP positions. Spain to Advance is the safer version of the Spain handicap, and USA/Belgium Over 2.5 is the cleaner angle than choosing a side.\n\nThis parlay pairs the two best soccer structures on the board: the safer knockout advance market and the strongest goals angle. It is still a parlay, so exposure stays small.\n\nMicks Verdict: Lotto B-, 0.25u. Play only at fair combined pricing." },
  { date: "2026-07-06", sport: "Multi-Sport", league: "MLB/FIFA World Cup", category: "Lotto Parlay", access: "Free", section: "lotto", originalTable: "Lotto Parlays", game: "Dodgers / Braves / Spain", pick: "Dodgers -1.5 + Braves ML + Spain to Advance", cardTitle: "Dodgers -1.5 + Braves ML + Spain to Advance", betType: "Lotto Parlay", market: "3-Leg Parlay", odds: "TBD", units: "0.15u", grade: "C+", confidence: "6.8/10", bestNumber: "Best available", lineNumber: "3-leg parlay", noBetCutoff: "Do not chase bad numbers", status: "Active", releaseStatus: "Lotto Released", sportsbook: "Shop best prices", risk: "Very High", shortAnalysis: "Small mixed-card lotto using two MLB positions plus the safer Spain advance angle.", writeup: "This is a small mixed-card lotto only. Dodgers -1.5 gives payout, Braves ML adds a cleaner side, and Spain to Advance anchors the soccer leg with the safer knockout-market structure.", analysis: "This is a higher-variance build because Dodgers -1.5 is a run-line leg. Keep the stake at 0.15u and do not treat it as a straight-card replacement.", fullAnalysis: "Lotto Parlay tab only. This is a higher-variance build because Dodgers -1.5 is a run-line leg. Keep the stake at 0.15u and do not treat it as a straight-card replacement.\n\nThe Dodgers run line creates payout but adds variance. Braves ML is the cleaner MLB side, and Spain to Advance is the safer soccer anchor. That combination is playable only as a small lotto.\n\nMicks Verdict: Lotto C+, 0.15u." },
  { date: "2026-07-06", sport: "Multi-Sport", league: "WNBA/MLB/FIFA World Cup", category: "Lotto Parlay", access: "Free", section: "lotto", originalTable: "Lotto Parlays", game: "Lynx / Braves / Spain", pick: "Minnesota Lynx ML + Braves ML + Spain to Advance", cardTitle: "Lynx ML + Braves ML + Spain to Advance", betType: "Lotto Parlay", market: "3-Leg Safer ML Parlay", odds: "TBD", units: "0.20u", grade: "C+", confidence: "6.9/10", bestNumber: "Best available", lineNumber: "3-leg safer ML parlay", noBetCutoff: "Do not chase bad combined pricing", status: "Active", releaseStatus: "Lotto Released", sportsbook: "Shop best prices", risk: "High", shortAnalysis: "Safer lotto build using Lynx ML instead of the large spread.", writeup: "This is the safer mixed-card parlay construction. Instead of forcing the Lynx -13 spread into a parlay, it uses Lynx ML with Braves ML and Spain to Advance.", analysis: "This is safer than using WNBA spreads, but still belongs as a small-stake parlay because prices can get inflated quickly. Keep exposure controlled.", fullAnalysis: "Lotto Parlay tab only. This is safer than using WNBA spreads, but still belongs as a small-stake parlay because prices can get inflated quickly.\n\nThe key is replacing Lynx -13 with Lynx ML. That removes spread risk from the WNBA leg and makes the parlay cleaner, but the combined price still needs to be fair.\n\nMicks Verdict: Lotto C+, 0.20u." }
]

const LONGSHOTS = []
const MAIN_PICKS = [...VIP_PICKS, ...FREE_PICKS]
const ALL_ROWS = [...MAIN_PICKS, ...PROPS, ...LOTTO_PARLAYS]

function makePublicVipTeaser(row = {}) {
  return { ...row, pick: "VIP Pick Locked", cardTitle: "VIP Pick Locked", game: row.league ? `${row.league} VIP Market Room` : "VIP Market Room", betType: "Members Only", category: "VIP Vault", access: "VIP", status: "VIP Locked", releaseStatus: "VIP Locked", grade: "VIP", odds: "Protected", units: "Members", bestNumber: "Members only", lineNumber: "Protected VIP line", noBetCutoff: "Protected portal", sportsbook: "VIP Portal", fullAnalysisLocked: true, fullAnalysis: undefined, analysis: undefined, writeup: "Full betting number, stake, sportsbook, and analysis are available inside the VIP Vault." }
}

function payloadForPublic() {
  return { success: true, source: "manual-july-6-all-cards-full-writeups", sourceOfTruth: "Micks Picks API override", date: "2026-07-06", warnings: [], activePicks: MAIN_PICKS, rows: MAIN_PICKS, records: MAIN_PICKS, picks: MAIN_PICKS, mainPicks: MAIN_PICKS, free: FREE_PICKS, vip: VIP_PICKS.map(makePublicVipTeaser), vipVault: [], props: PROPS, propsLab: PROPS, lottoParlays: LOTTO_PARLAYS, lotto: LOTTO_PARLAYS, parlays: LOTTO_PARLAYS, longshots: LONGSHOTS, allRows: ALL_ROWS }
}

function payloadForVip() {
  return { success: true, source: "manual-july-6-all-cards-full-writeups-vip", sourceOfTruth: "Micks Picks API override", date: "2026-07-06", warnings: [], activePicks: MAIN_PICKS, rows: MAIN_PICKS, records: MAIN_PICKS, picks: MAIN_PICKS, mainPicks: MAIN_PICKS, free: FREE_PICKS, vip: VIP_PICKS, vipVault: VIP_PICKS, props: PROPS, propsLab: PROPS, lottoParlays: LOTTO_PARLAYS, lotto: LOTTO_PARLAYS, parlays: LOTTO_PARLAYS, longshots: LONGSHOTS, allRows: ALL_ROWS }
}

export default async function handler(req, res) {
  res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate, max-age=0")
  res.status(200).json(String(req.query?.vip || "").trim() === "1" ? payloadForVip() : payloadForPublic())
}
