function rec(section,data){const access=data.Access||(section==='VIP'?'VIP':'Free');return{...data,section,__section:section,originalTable:section,access,Access:access,date:data.Date,sport:data.Sport,league:data.League,game:data.Game,pick:data.Pick,market:data['Bet Type']||data.Prop||'',odds:data.Odds||'',grade:data.Grade||'',units:data.Units||'',confidence:data.Confidence||'',status:data.Status||'Pending',notes:data.Writeup||data['Full Analysis']||'',source:'Micks Picks July 11 merged card'}}

const vip=[
rec('VIP',{Date:'2026-07-11',Sport:'MMA',League:'UFC 329',Game:'Max Holloway vs Conor McGregor',Pick:'Max Holloway ML','Bet Type':'Moneyline',Odds:'-210',Grade:'A-',Units:'1.00','Best Number':'-210 or better','No-Bet Cutoff':'-240',Confidence:'8.7/10',Status:'Pending',Access:'VIP',Featured:'Yes','Official Bet':'Yes','Pick of the Day Eligible':'Yes','Full Analysis':'Holloway owns the decisive activity, durability, volume, and recent-form advantages. McGregor enters after nearly five years away, which creates major timing and cardio uncertainty. The moneyline is preferred over a method prop because it protects against a decision while still backing the more reliable fighter.','Risk':'McGregor early power and five-round variance.'}),
rec('VIP',{Date:'2026-07-11',Sport:'Soccer',League:'FIFA World Cup',Game:'Norway vs England',Pick:'England to Advance','Bet Type':'To Advance',Odds:'-250',Grade:'A-',Units:'1.00','Best Number':'-250 or better','No-Bet Cutoff':'-285',Confidence:'8.5/10',Status:'Pending',Access:'VIP',Featured:'Yes','Official Bet':'Yes','Full Analysis':'England has won 15 of its last 16 competitive matches and brings the deeper midfield and bench. Norway is dangerous through Haaland and transitions, so the to-advance market is preferred to the 90-minute moneyline because it protects against extra time.','Risk':'Extreme Miami heat and Haaland transition threat.'})]

const free=[
rec('Free',{Date:'2026-07-11',Sport:'Baseball',League:'MLB',Game:'Seattle Mariners vs Tampa Bay Rays',Pick:'Seattle Mariners ML','Bet Type':'Moneyline',Grade:'B+',Units:'0.75','Best Number':'-135 or better','No-Bet Cutoff':'-150',Confidence:'7.8/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'Logan Gilbert enters in strong form and holds the starting-pitching edge over Griffin Jax. Seattle is the preferred side if the price remains manageable.'}),
rec('Free',{Date:'2026-07-11',Sport:'Basketball',League:'WNBA',Game:'New York Liberty vs Minnesota Lynx',Pick:'New York Liberty +5.5','Bet Type':'Spread',Odds:'-110',Grade:'B+',Units:'0.75','Best Number':'+5.5','No-Bet Cutoff':'+4.5',Confidence:'7.8/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Featured:'Yes',Writeup:'Doc’s Sports explicitly backs New York +5.5, while VSiN’s TSI projection makes Minnesota only a 4-point favorite. That creates roughly 1.5 points of model value at the posted spread. New York’s injury situation prevents an A grade, but the number is preferable to laying a moneyline price with Minnesota.'}),
rec('Free',{Date:'2026-07-11',Sport:'Basketball',League:'WNBA',Game:'Phoenix Mercury vs Las Vegas Aces',Pick:'Over 170.5','Bet Type':'Game Total',Odds:'-110',Grade:'B+',Units:'0.75','Best Number':'170.5','No-Bet Cutoff':'172',Confidence:'8.0/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'VSiN’s TSI projects 171.5 and identifies the Over as one of the preferred plays, supported by positive Las Vegas regression and recent Phoenix overperformance that may normalize. Doc’s and VSiN disagree on the side, so the total is the cleaner market.'}),
rec('Free',{Date:'2026-07-11',Sport:'Baseball',League:'MLB',Game:'Boston Red Sox vs New York Mets',Pick:'Boston Red Sox ML','Bet Type':'Moneyline',Odds:'-128',Grade:'B',Units:'0.50','Best Number':'-128 or better','No-Bet Cutoff':'-140',Confidence:'7.2/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'Doc’s Sports backs Boston at -128. Boston owns the stronger season-long run prevention profile, the better bullpen save rate, and a cleaner defensive record. The Mets’ starting-pitching edge keeps this at a moderate stake rather than a premium release.'}),
rec('Free',{Date:'2026-07-11',Sport:'Soccer',League:'FIFA World Cup',Game:'Argentina vs Switzerland',Pick:'Argentina to Advance','Bet Type':'To Advance',Grade:'B+',Units:'0.75','Best Number':'-300 or better','No-Bet Cutoff':'-340',Confidence:'7.9/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'Argentina retains the superior attacking ceiling and knockout experience. Switzerland is disciplined enough to make the 90-minute line uncomfortable, so advancement is the safer market.'})]

const propsLab=[
rec('Props',{Date:'2026-07-11',Sport:'MMA',League:'UFC 329',Game:'Max Holloway vs Conor McGregor',Pick:'Max Holloway by KO/TKO',Prop:'Method of Victory',Grade:'B+',Units:'0.50','Best Number':'+140 or better','No-Bet Cutoff':'+115',Confidence:'7.6/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'McGregor inactivity and likely late-fight cardio decline create a finish window for Holloway after sustained volume.'}),
rec('Props',{Date:'2026-07-11',Sport:'MMA',League:'UFC 329',Game:'Cory Sandhagen vs Mario Bautista',Pick:'Cory Sandhagen by Decision',Prop:'Method of Victory',Odds:'+190',Grade:'B',Units:'0.50',Confidence:'7.2/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'Sandhagen has the range, elite-level experience, and five-round composure to manage Bautista pressure and win minutes.'}),
rec('Props',{Date:'2026-07-11',Sport:'MMA',League:'UFC 329',Game:'Adrian Yanez vs Cody Garbrandt',Pick:'Adrian Yanez by KO/TKO',Prop:'Method of Victory',Odds:'+100',Grade:'B',Units:'0.50',Confidence:'7.1/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'Yanez carries the cleaner boxing and sustained pressure against an opponent with recurring durability concerns.'}),
rec('Props',{Date:'2026-07-11',Sport:'Soccer',League:'FIFA World Cup',Game:'Norway vs England',Pick:'Erling Haaland Anytime Scorer',Player:'Erling Haaland',Prop:'Anytime Scorer',Grade:'B-',Units:'0.35','Best Number':'+120 or better','No-Bet Cutoff':'+100',Confidence:'6.8/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'Haaland enters with seven tournament goals and remains Norway’s highest-leverage route to scoring.'})]

const lottoParlays=[
rec('Lotto',{Date:'2026-07-11',Sport:'Multi-Sport',League:'World Cup / UFC',Game:'Norway vs England; Holloway vs McGregor',Pick:'England to Advance + Max Holloway ML','Bet Type':'2-Leg Parlay',Grade:'B+',Units:'0.50',Confidence:'7.8/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'A two-leg combination of the two highest-confidence advancement and moneyline positions.'}),
rec('Lotto',{Date:'2026-07-11',Sport:'Basketball',League:'WNBA',Game:'Liberty vs Lynx; Mercury vs Aces',Pick:'Liberty +5.5 + Mercury/Aces Over 170.5','Bet Type':'2-Leg Parlay',Grade:'B',Units:'0.25',Confidence:'7.0/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'Small-stake WNBA combination built from the two strongest research merges: New York receives spread value versus the VSiN projection, while the Las Vegas-Phoenix total is the cleaner consensus angle after conflicting side opinions.'})]

const longshots=[
rec('Longshots',{Date:'2026-07-11',Sport:'MMA',League:'UFC 329',Game:'Paddy Pimblett vs Benoit Saint Denis',Pick:'Paddy Pimblett by Submission in Rounds 2 or 3',Prop:'Method / Round',Odds:'+1200',Grade:'C+',Units:'0.15',Confidence:'5.8/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'Saint Denis aggression can create late grappling openings if his pace fades.'}),
rec('Longshots',{Date:'2026-07-11',Sport:'MMA',League:'UFC 329',Game:'Wang Cong vs Tracy Cortez',Pick:'Wang Cong by Decision',Prop:'Method of Victory',Odds:'+245',Grade:'C+',Units:'0.20',Confidence:'5.9/10',Status:'Pending',Access:'Free','Official Bet':'Yes',Writeup:'Wang’s striking volume provides an upset path if she keeps the fight at range and wins rounds.'})]

const publicRows=[...free,...propsLab,...lottoParlays,...longshots],allRows=[...vip,...publicRows]
export default function handler(req,res){res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');res.status(200).json({ok:true,success:true,source:'micks-picks-july-11-docs-vsin-merged-card',date:'2026-07-11',vip,vipPicks:vip,vipVault:vip,free,freePicks:free,props:propsLab,propsLab,lottoParlays,lotto:lottoParlays,parlays:lottoParlays,longshots,mainPicks:[...vip,...free],activePicks:allRows,rows:allRows,records:allRows,picks:allRows,allRows,publicRows,message:'July 11 card updated with Doc’s Sports and VSiN research.'})}